# Generated by Django 5.1.15 on 2026-06-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='اسم المعيار')),
                ('weight', models.FloatField(default=1.0, verbose_name='الوزن')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'معيار تقييم',
                'verbose_name_plural': 'معايير التقييم',
            },
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('ayah_count', models.IntegerField()),
                ('revelation_type', models.CharField(choices=[('makki', 'مكية'), ('madani', 'مدنية')], max_length=10)),
            ],
            options={
                'verbose_name': 'سورة',
                'verbose_name_plural': 'السور',
                'ordering': ['id'],
            },
        ),
    ]
