# Generated by Django 6.0.6 on 2026-06-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='رقم الجزء')),
                ('ayah_count', models.IntegerField(verbose_name='عدد الآيات')),
            ],
            options={
                'verbose_name': 'جزء',
                'verbose_name_plural': 'الأجزاء',
                'ordering': ['number'],
            },
        ),
    ]
