# Generated by Django 6.0.6 on 2026-07-03 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_juz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hizb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='رقم الحزب')),
                ('number_in_juz', models.IntegerField(verbose_name='ترتيبه في الجزء')),
                ('juz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hizbs', to='references.juz')),
            ],
            options={
                'verbose_name': 'حزب',
                'verbose_name_plural': 'الأحزاب',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Rub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='رقم الربع')),
                ('number_in_hizb', models.IntegerField(verbose_name='ترتيبه في الحزب')),
                ('hizb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubs', to='references.hizb')),
            ],
            options={
                'verbose_name': 'ربع',
                'verbose_name_plural': 'الأرباع',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_surah', models.IntegerField(verbose_name='رقم الآية في السورة')),
                ('page', models.IntegerField(verbose_name='رقم الصفحة')),
                ('text_uthmani', models.TextField(verbose_name='النص العثماني')),
                ('text_normalized', models.TextField(blank=True, help_text='نص بدون تشكيل للبحث', verbose_name='النص المجرد')),
                ('sajdah', models.BooleanField(default=False, verbose_name='سجدة')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='references.surah')),
                ('rub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='references.rub')),
            ],
            options={
                'verbose_name': 'آية',
                'verbose_name_plural': 'الآيات',
                'ordering': ['surah_id', 'number_in_surah'],
                'indexes': [models.Index(fields=['page'], name='references__page_914553_idx'), models.Index(fields=['rub'], name='references__rub_id_159c99_idx')],
                'constraints': [models.UniqueConstraint(fields=('surah', 'number_in_surah'), name='uniq_ayah_surah_number')],
            },
        ),
    ]
