# Generated by Django 6.0.6 on 2026-07-04 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_hizb_rub_ayah'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='رقم الثمن')),
                ('number_in_hizb', models.IntegerField(verbose_name='ترتيبه في الحزب')),
                ('page', models.IntegerField(verbose_name='صفحة البداية')),
                ('start_ayah_number', models.IntegerField(verbose_name='آية البداية')),
                ('ayah_id_global', models.IntegerField(help_text='ترقيم متسلسل للآيات في مصحف ورش', unique=True, verbose_name='رقم الآية الكلي (ورش)')),
                ('rub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumns', to='references.rub')),
                ('start_surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumn_starts', to='references.surah', verbose_name='سورة البداية')),
            ],
            options={
                'verbose_name': 'ثمن',
                'verbose_name_plural': 'الأثمان',
                'ordering': ['number'],
            },
        ),
    ]
