# Generated by Django 5.1.15 on 2026-06-26 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacherabsence'),
        ('circles', '0003_circle_description_circle_schedule_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='accounts.teacherabsence', verbose_name='طلب الغياب')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='circles.circle', verbose_name='الحلقة')),
                ('substitute_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitution_duties', to=settings.AUTH_USER_MODEL, verbose_name='المعلم البديل')),
            ],
            options={
                'verbose_name': 'تعويض معلم',
                'verbose_name_plural': 'تعويضات المعلمين',
                'unique_together': {('absence', 'circle')},
            },
        ),
        migrations.CreateModel(
            name='SessionSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('conducted', 'تمت'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='circles.session', verbose_name='الحصة')),
                ('substitute_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المعلم البديل')),
                ('substitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_substitutions', to='accounts.teachersubstitution', verbose_name='التعويض')),
            ],
            options={
                'verbose_name': 'تعويض حصة',
                'verbose_name_plural': 'تعويضات الحصص',
            },
        ),
    ]
