# Generated by Django 6.0.6 on 2026-06-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teachersubstitution_sessionsubstitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, max_length=100, verbose_name='المستوى'),
        ),
        migrations.AddField(
            model_name='user',
            name='memorization_amount',
            field=models.CharField(blank=True, max_length=100, verbose_name='مقدار الحفظ'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, verbose_name='التخصص'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='الولاية'),
        ),
    ]
