# Generated by Django 6.0.6 on 2026-07-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_batch_user_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='رقم الدفعة'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('name', 'year'), name='unique_batch_name_per_year'),
        ),
    ]
