# Generated by Django 6.0.6 on 2026-06-30 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم القالب')),
                ('category', models.CharField(choices=[('hifz', 'شهادة حفظ'), ('murajaa', 'شهادة مراجعة'), ('exam', 'شهادة امتحان'), ('completion', 'شهادة إتمام'), ('distinction', 'شهادة تميز')], max_length=30, verbose_name='الفئة')),
                ('background_image', models.ImageField(blank=True, upload_to='certificate_templates/', verbose_name='صورة الخلفية')),
                ('header_text', models.TextField(default='بسم الله الرحمن الرحيم', verbose_name='النص العلوي')),
                ('body_template', models.TextField(help_text='استخدم {student_name}, {circle_name}, {date}, {details}', verbose_name='قالب النص')),
                ('footer_text', models.TextField(blank=True, verbose_name='النص السفلي')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قالب شهادة',
                'verbose_name_plural': 'قوالب الشهادات',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الشهادة')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('issued', 'صادرة'), ('revoked', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('details', models.TextField(blank=True, verbose_name='تفاصيل')),
                ('pdf_file', models.FileField(blank=True, upload_to='certificates/', verbose_name='ملف PDF')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL, verbose_name='صادر عن')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.certificatetemplate', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'شهادة',
                'verbose_name_plural': 'الشهادات',
                'ordering': ['-issue_date'],
            },
        ),
    ]
