# Generated by Django 6.0.6 on 2026-06-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('pending_upload', 'بانتظار رفع الملف'), ('issued', 'صادرة'), ('revoked', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
    ]
