# Generated by Django 6.0.6 on 2026-06-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificate_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSeq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='التاريخ')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='العدد')),
            ],
            options={
                'verbose_name': 'تسلسل شهادات',
                'verbose_name_plural': 'تسلسل الشهادات',
            },
        ),
    ]
