# Generated by Django 6.0.6 on 2026-07-04 03:28

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificateseq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='certificates/', validators=[apps.core.validators.validate_pdf], verbose_name='ملف PDF'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='certificate_templates/', validators=[apps.core.validators.validate_file_size], verbose_name='صورة الخلفية'),
        ),
    ]
