# Generated by Django 5.1.15 on 2026-06-25 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleenrollment',
            name='current_surah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.surah', verbose_name='السورة الحالية'),
        ),
    ]
