# Generated by Django 5.1.15 on 2026-06-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_circleenrollment_current_surah'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='circle',
            name='schedule_days',
            field=models.JSONField(blank=True, default=list, verbose_name='أيام الحلقة'),
        ),
        migrations.AddField(
            model_name='circle',
            name='schedule_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الحلقة'),
        ),
        migrations.AddField(
            model_name='circle',
            name='surah_range',
            field=models.CharField(blank=True, max_length=255, verbose_name='نطاق السور'),
        ),
        migrations.AddField(
            model_name='circleenrollment',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المغادرة'),
        ),
    ]
