# Generated by Django 6.0.6 on 2026-06-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_circle_description_circle_schedule_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'حصة', 'verbose_name_plural': 'الحصص'},
        ),
        migrations.AddField(
            model_name='session',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المدة (دقائق)'),
        ),
        migrations.AddField(
            model_name='session',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='معرف الاجتماع'),
        ),
        migrations.AddField(
            model_name='session',
            name='meeting_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='كلمة مرور الاجتماع'),
        ),
        migrations.AddField(
            model_name='session',
            name='meeting_platform',
            field=models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('other', 'أخرى')], max_length=20, verbose_name='منصة الاجتماع'),
        ),
        migrations.AddField(
            model_name='session',
            name='meeting_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='رابط الاجتماع'),
        ),
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='session',
            name='recording_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='رابط التسجيل'),
        ),
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('in_person', 'حضوري'), ('online', 'عن بُعد')], default='in_person', max_length=20, verbose_name='نوع الحصة'),
        ),
    ]
