# Generated by Django 6.0.6 on 2026-06-26 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0005_sessionstudentnote'),
        ('references', '0002_juz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_date', models.DateField(verbose_name='التاريخ المقترح')),
                ('proposed_time', models.TimeField(blank=True, null=True, verbose_name='الوقت المقترح')),
                ('reason', models.TextField(blank=True, verbose_name='سبب التعديل')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reschedules', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='circles.session')),
            ],
            options={
                'verbose_name': 'طلب تعديل موعد حصة',
                'verbose_name_plural': 'طلبات تعديل موعد الحصص',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionLessonToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayah_from', models.IntegerField(blank=True, null=True, verbose_name='من الآية')),
                ('ayah_to', models.IntegerField(blank=True, null=True, verbose_name='إلى الآية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('toggled_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_toggles', to='circles.session')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_toggles', to='references.surah')),
            ],
            options={
                'verbose_name': 'تبديل درس',
                'verbose_name_plural': 'تبديلات الدروس',
                'unique_together': {('session', 'surah')},
            },
        ),
    ]
