# Generated by Django 6.0.6 on 2026-06-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0006_sessionreschedulerequest_sessionlessontoggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الحصة'),
        ),
    ]
