# Generated by Django 6.0.6 on 2026-06-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0007_session_time_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='مكان الحصة'),
        ),
    ]
