# Generated by Django 6.0.6 on 2026-06-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0008_session_location_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='batch_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الدفعة'),
        ),
    ]
