# Generated by Django 6.0.6 on 2026-06-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0009_circle_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('active', 'نشط'), ('inactive', 'منتهي'), ('dropped', 'منسحب')], default='active', max_length=20),
        ),
    ]
