# Generated by Django 6.0.6 on 2026-06-30 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0010_add_pending_enrollment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField(verbose_name='رقم الدور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='circles.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_turns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دور تسميع',
                'verbose_name_plural': 'أدوار التسميع',
                'ordering': ['turn_number'],
                'unique_together': {('session', 'turn_number')},
            },
        ),
    ]
