# Generated by Django 6.0.6 on 2026-07-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0011_sessionturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='turns_closed',
            field=models.BooleanField(default=False, verbose_name='إغلاق التسجيل في الأدوار'),
        ),
    ]
