# Generated by Django 6.0.6 on 2026-07-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0012_session_turns_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء'),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('scheduled', 'مجدولة'), ('confirmation_open', 'فتح التأكيد'), ('turn_taking_open', 'فتح الأدوار'), ('live', 'جارية'), ('ended', 'منتهية')], default='draft', max_length=30, verbose_name='حالة الحصة'),
        ),
    ]
