# Generated by Django 6.0.6 on 2026-07-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0014_fix_existing_session_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='surah_range',
        ),
        migrations.AddField(
            model_name='session',
            name='meeting_source',
            field=models.CharField(choices=[('classroom', 'قاعة المعلم الدائمة'), ('external', 'رابط خارجي')], default='classroom', max_length=20, verbose_name='مصدر رابط الاجتماع'),
        ),
    ]
