# Generated by Django 6.0.6 on 2026-07-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0015_remove_circle_surah_range_session_meeting_source'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['circle', 'status'], name='circles_ses_circle__20d87f_idx'),
        ),
    ]
