# Generated by Django 6.0.6 on 2026-07-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0016_session_circles_ses_circle__20d87f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='circle_type',
            field=models.CharField(choices=[('ahkam', 'أحكام'), ('hifd', 'حفظ'), ('murajaa', 'مراجعة')], default='hifd', max_length=20, verbose_name='نوع الحلقة'),
        ),
    ]
