# Generated by Django 6.0.6 on 2026-07-04 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0017_circle_circle_type'),
        ('references', '0003_hizb_rub_ayah'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='circleenrollment',
            index=models.Index(fields=['student', 'status'], name='circles_cir_student_e1f1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='circleenrollment',
            index=models.Index(fields=['circle', 'status'], name='circles_cir_circle__94a4e6_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_date'], name='circles_ses_session_d9528e_idx'),
        ),
    ]
