# Generated by Django 6.0.6 on 2026-07-06 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_batch_user_batch'),
        ('circles', '0018_circleenrollment_circles_cir_student_e1f1fc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circles', to='accounts.batch', verbose_name='الدفعة'),
        ),
    ]
