# Generated by Django 6.0.6 on 2026-07-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0019_circle_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='batch_number',
        ),
    ]
