# Generated by Django 6.0.6 on 2026-06-26 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circles', '0005_sessionstudentnote'),
        ('references', '0002_juz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorizationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hifz', 'حفظ جديد'), ('murajaa', 'مراجعة')], default='hifz', max_length=20, verbose_name='النوع')),
                ('ayah_from', models.IntegerField()),
                ('ayah_to', models.IntegerField()),
                ('status', models.CharField(choices=[('memorizing', 'في طور الحفظ'), ('reviewed', 'مراجع'), ('tested', 'مختبر'), ('mastered', 'متقن'), ('weak', 'ضعيف')], default='memorizing', max_length=20)),
                ('revision_count', models.IntegerField(default=0, verbose_name='عدد مرات المراجعة')),
                ('last_revised_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مراجعة')),
                ('tested_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorization_progress', to='circles.circleenrollment')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='progress_records', to='references.surah')),
                ('tested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقدم حفظ/مراجعة',
                'verbose_name_plural': 'تقدم الحفظ والمراجعة',
            },
        ),
        migrations.CreateModel(
            name='RecitationGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('max_score', models.FloatField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grades', to='references.evaluationcriterion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitation_grades', to='circles.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitation_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درجة تلاوة',
                'verbose_name_plural': 'درجات التلاوة',
            },
        ),
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('review', 'طلب مراجعة'), ('recitation', 'طلب تسميع')], max_length=20, verbose_name='نوع الطلب')),
                ('ayah_from', models.IntegerField(blank=True, null=True, verbose_name='من الآية')),
                ('ayah_to', models.IntegerField(blank=True, null=True, verbose_name='إلى الآية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الطالب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='circles.circle')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to=settings.AUTH_USER_MODEL)),
                ('surah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.surah', verbose_name='السورة')),
            ],
            options={
                'verbose_name': 'طلب مراجعة/تسميع',
                'verbose_name_plural': 'طلبات المراجعة والتسميع',
                'ordering': ['-created_at'],
            },
        ),
    ]
