# Generated by Django 6.0.6 on 2026-06-26 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0006_sessionreschedulerequest_sessionlessontoggle'),
        ('memorization', '0001_initial'),
        ('references', '0002_juz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_category', models.CharField(choices=[('HIFDH', 'تسميع جديد'), ('MURAJAAH', 'مراجعة')], max_length=20, verbose_name='نوع التسجيل')),
                ('start_ayah', models.IntegerField(verbose_name='من الآية')),
                ('end_ayah', models.IntegerField(verbose_name='إلى الآية')),
                ('completed_pages', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='عدد الصفحات')),
                ('evaluation_grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('ممتاز', 'ممتاز'), ('جيد جداً', 'جيد جداً'), ('جيد', 'جيد'), ('ضعيف', 'ضعيف')], max_length=10, verbose_name='الدرجة التقديرية')),
                ('teacher_notes', models.TextField(blank=True, verbose_name='ملاحظات المعلم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='circles.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to=settings.AUTH_USER_MODEL)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='references.surah', verbose_name='السورة')),
            ],
            options={
                'verbose_name': 'سجل تقدم',
                'verbose_name_plural': 'سجلات التقدم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hifdh_ayahs', models.IntegerField(default=0, verbose_name='إجمالي آيات الحفظ')),
                ('total_murajaah_ayahs', models.IntegerField(default=0, verbose_name='إجمالي آيات المراجعة')),
                ('total_hifdh_pages', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='إجمالي صفحات الحفظ')),
                ('total_murajaah_pages', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='إجمالي صفحات المراجعة')),
                ('completed_juz', models.IntegerField(default=0, verbose_name='الأجزاء المنجزة')),
                ('current_juz', models.IntegerField(default=1, verbose_name='الجزء الحالي')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='achievement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إنجاز طالب',
                'verbose_name_plural': 'إنجازات الطلاب',
            },
        ),
    ]
