# Generated by Django 6.0.6 on 2026-07-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0002_progresslog_studentachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='meeting_platform',
            field=models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('other', 'أخرى')], max_length=20, verbose_name='منصة الاجتماع'),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='meeting_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='رابط الاجتماع'),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='preferred_days',
            field=models.JSONField(blank=True, default=list, verbose_name='الأيام المفضلة'),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='preferred_times',
            field=models.JSONField(blank=True, default=list, verbose_name='الأوقات المفضلة'),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ المراجعة'),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت المراجعة'),
        ),
    ]
