# Generated by Django 6.0.6 on 2026-07-03 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0003_add_review_request_availability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='بداية الأسبوع')),
                ('goal_type', models.CharField(choices=[('hifz', 'حفظ جديد'), ('murajaa', 'مراجعة'), ('pages', 'عدد الصفحات'), ('attendance', 'الالتزام بالحضور')], max_length=20, verbose_name='نوع الهدف')),
                ('target_value', models.FloatField(verbose_name='القيمة المستهدفة')),
                ('achieved_value', models.FloatField(default=0, verbose_name='القيمة المحققة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'هدف أسبوعي',
                'verbose_name_plural': 'الأهداف الأسبوعية',
                'ordering': ['-week_start', 'goal_type'],
                'unique_together': {('student', 'week_start', 'goal_type')},
            },
        ),
    ]
