# Generated by Django 6.0.6 on 2026-07-03 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0014_fix_existing_session_status'),
        ('memorization', '0005_add_assigned_by_to_weekly_goal'),
        ('references', '0003_hizb_rub_ayah'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_MEMORIZED', 'لم يُحفظ'), ('IN_PROGRESS', 'قيد الحفظ'), ('MEMORIZED', 'محفوظ'), ('NEEDS_REVIEW', 'يحتاج مراجعة'), ('WEAK', 'ضعيف'), ('MASTERED', 'متقن')], default='NOT_MEMORIZED', max_length=20)),
                ('memorized_at', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('review_interval_days', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memorization_records', to='circles.circle')),
                ('rub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memorization_records', to='references.rub', verbose_name='الربع')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorization_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل حفظ',
                'verbose_name_plural': 'سجلات الحفظ',
                'ordering': ['student', 'rub__number'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.CharField(max_length=20, verbose_name='التقييم')),
                ('mistakes_count', models.IntegerField(default=0, verbose_name='عدد الأخطاء')),
                ('teacher_notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('previous_interval', models.IntegerField(default=0)),
                ('new_interval', models.IntegerField(default=0)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='memorization.memorizationrecord')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_review_evaluations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_evaluations', to='circles.session')),
            ],
            options={
                'verbose_name': 'سجل مراجعة',
                'verbose_name_plural': 'سجل المراجعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='memorizationrecord',
            index=models.Index(fields=['student', 'next_review_date'], name='memorizatio_student_78df77_idx'),
        ),
        migrations.AddIndex(
            model_name='memorizationrecord',
            index=models.Index(fields=['student', 'status'], name='memorizatio_student_cb07db_idx'),
        ),
        migrations.AddConstraint(
            model_name='memorizationrecord',
            constraint=models.UniqueConstraint(fields=('student', 'rub'), name='uniq_memorization_student_rub'),
        ),
    ]
