# Generated by Django 6.0.6 on 2026-07-03 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0006_memorizationrecord_reviewhistory_and_more'),
        ('references', '0003_hizb_rub_ayah'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('hifz', 'حفظ جديد'), ('murajaa', 'مراجعة')], max_length=20, verbose_name='نوع المهمة')),
                ('ayah_from', models.IntegerField(verbose_name='من الآية')),
                ('ayah_to', models.IntegerField(verbose_name='إلى الآية')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('done', 'تم الإنجاز'), ('validated', 'تم التحقق'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='المسند من')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_tasks', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='references.surah', verbose_name='السورة')),
            ],
            options={
                'verbose_name': 'مهمة حفظ/مراجعة',
                'verbose_name_plural': 'مهام الحفظ والمراجعة',
                'ordering': ['-created_at'],
            },
        ),
    ]
