# Generated by Django 6.0.6 on 2026-07-03 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0007_studytask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyGoal',
        ),
    ]
