# Generated by Django 6.0.6 on 2026-07-04 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0014_fix_existing_session_status'),
        ('memorization', '0008_delete_weeklygoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytask',
            name='circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_tasks', to='circles.circle', verbose_name='الحلقة'),
        ),
    ]
