# Generated by Django 6.0.6 on 2026-07-04 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0009_studytask_circle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studytask',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_tasks', to=settings.AUTH_USER_MODEL, verbose_name='تم التحقق بواسطة'),
        ),
    ]
