# Generated by Django 6.0.6 on 2026-07-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0010_studytask_validated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrequest',
            name='type',
            field=models.CharField(choices=[('review', 'طلب مراجعة'), ('recitation', 'طلب تسميع'), ('question', 'سؤال للمعلم')], max_length=20, verbose_name='نوع الطلب'),
        ),
    ]
