# Generated by Django 6.0.6 on 2026-07-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0011_alter_reviewrequest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='response',
            field=models.TextField(blank=True, verbose_name='رد المعلم'),
        ),
    ]
