# Generated by Django 6.0.6 on 2026-07-04 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0017_circle_circle_type'),
        ('memorization', '0012_reviewrequest_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrequest',
            name='type',
            field=models.CharField(choices=[('recitation', 'تسميع'), ('question', 'سؤال للمعلم')], max_length=20, verbose_name='نوع الطلب'),
        ),
        migrations.CreateModel(
            name='PrivateSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='الوقت')),
                ('meeting_url', models.URLField(blank=True, max_length=500, verbose_name='رابط الاجتماع')),
                ('meeting_platform', models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('other', 'أخرى')], max_length=20, verbose_name='منصة الاجتماع')),
                ('status', models.CharField(choices=[('scheduled', 'مجدولة'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='scheduled', max_length=20)),
                ('student_notes', models.TextField(blank=True, verbose_name='طلب الطالب')),
                ('result_mark', models.CharField(blank=True, max_length=50, verbose_name='التقييم')),
                ('result_notes', models.TextField(blank=True, verbose_name='ملاحظات المعلم')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_sessions', to='circles.circle', verbose_name='الحلقة')),
                ('source_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_session', to='memorization.reviewrequest', verbose_name='الطلب المصدر')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_sessions', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_sessions_taught', to=settings.AUTH_USER_MODEL, verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'جلسة خاصة',
                'verbose_name_plural': 'الجلسات الخاصة',
                'ordering': ['-scheduled_date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='memorizatio_student_996133_idx')],
            },
        ),
    ]
