# Generated by Django 6.0.6 on 2026-07-04 12:28

from django.db import migrations


def review_to_recitation(apps, schema_editor):
    ReviewRequest = apps.get_model("memorization", "ReviewRequest")
    ReviewRequest.objects.filter(type="review").update(type="recitation")


def recitation_to_review(apps, schema_editor):
    # Irreversible in practice (the two are merged); no-op on the way back.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0013_alter_reviewrequest_type_privatesession'),
    ]

    operations = [
        migrations.RunPython(review_to_recitation, recitation_to_review),
    ]
