# Generated by Django 6.0.6 on 2026-07-04 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0018_circleenrollment_circles_cir_student_e1f1fc_idx_and_more'),
        ('memorization', '0014_merge_review_into_recitation'),
        ('references', '0003_hizb_rub_ayah'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studytask',
            index=models.Index(fields=['student', 'status'], name='memorizatio_student_6cdbac_idx'),
        ),
    ]
