# Generated by Django 6.0.6 on 2026-07-07 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0019_circle_batch'),
        ('memorization', '0015_studytask_memorizatio_student_6cdbac_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentachievement',
            name='total_hifdh_thumns',
            field=models.IntegerField(default=0, verbose_name='إجمالي أثمان الحفظ'),
        ),
        migrations.AddField(
            model_name='studentachievement',
            name='total_murajaah_thumns',
            field=models.IntegerField(default=0, verbose_name='إجمالي أثمان المراجعة'),
        ),
        migrations.AddField(
            model_name='studytask',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AddField(
            model_name='studytask',
            name='session',
            field=models.ForeignKey(blank=True, help_text='الحصة التي أُسندت المهمة عقبها', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_tasks', to='circles.session', verbose_name='الحصة المرتبطة'),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='log_category',
            field=models.CharField(choices=[('HIFDH', 'حفظ جديد'), ('MURAJAAH', 'مراجعة'), ('RECITATION', 'تلاوة')], max_length=20, verbose_name='نوع التسجيل'),
        ),
        migrations.AlterField(
            model_name='studytask',
            name='task_type',
            field=models.CharField(choices=[('hifz', 'حفظ جديد'), ('murajaa', 'مراجعة'), ('recitation', 'تلاوة')], max_length=20, verbose_name='نوع المهمة'),
        ),
    ]
