# Generated by Django 6.0.6 on 2026-07-09 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0016_studentachievement_total_hifdh_thumns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslog',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='النقطة من 20'),
        ),
    ]
