# Generated by Django 6.0.6 on 2026-07-13 07:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0020_remove_circle_batch_number'),
        ('memorization', '0018_progresslog_updated_at_progresslog_updated_by'),
        ('references', '0004_thumn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslog',
            name='hizb',
            field=models.PositiveIntegerField(default=0, verbose_name='أحزاب'),
        ),
        migrations.AddField(
            model_name='progresslog',
            name='thumn',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='أثمان'),
        ),
        migrations.AddField(
            model_name='progresslog',
            name='total_thumns',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='إجمالي الأثمان'),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='end_ayah',
            field=models.IntegerField(blank=True, null=True, verbose_name='إلى الآية'),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='circles.session'),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='start_ayah',
            field=models.IntegerField(blank=True, null=True, verbose_name='من الآية'),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='surah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='references.surah', verbose_name='السورة'),
        ),
        migrations.AddIndex(
            model_name='progresslog',
            index=models.Index(fields=['student', 'log_category'], name='memorizatio_student_8adbea_idx'),
        ),
    ]
