import os
import subprocess
import tempfile

from django.conf import settings
from django.template.loader import render_to_string
from django.utils import timezone

from .models import Certificate, CertificateTemplate


LATEX_SPECIAL_CHARS = {
    "#": r"\#",
    "$": r"\$",
    "%": r"\%",
    "&": r"\&",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
    "\\": r"\textbackslash{}",
}


def escape_latex(text: str) -> str:
    result = []
    for ch in text:
        result.append(LATEX_SPECIAL_CHARS.get(ch, ch))
    return "".join(result)


def generate_certificate_number():
    today = timezone.now().date()
    prefix = "CERT"
    date_str = today.strftime("%Y%m%d")
    count = Certificate.objects.filter(issue_date=today).count()
    return f"{prefix}-{date_str}-{count + 1:04d}"


def generate_certificate_pdf(certificate: Certificate) -> bytes:
    template = certificate.template
    student = certificate.student
    issue_date = certificate.issue_date or timezone.now().date()
    body = template.body_template.format(
        student_name=student.full_name_ar,
        circle_name=certificate.metadata.get("circle_name", ""),
        details=certificate.details,
    )

    context = {
        "student_name": escape_latex(student.full_name_ar),
        "circle_name": escape_latex(certificate.metadata.get("circle_name", "")),
        "date": issue_date.strftime("%d/%m/%Y"),
        "details": escape_latex(certificate.details),
        "certificate_number": certificate.certificate_number,
        "header_text": escape_latex(template.header_text),
        "body": escape_latex(body),
        "footer_text": escape_latex(template.footer_text),
    }

    tex_source = render_to_string("certificates/certificate.tex", context)

    with tempfile.TemporaryDirectory() as tmpdir:
        tex_path = os.path.join(tmpdir, "certificate.tex")
        with open(tex_path, "w", encoding="utf-8") as f:
            f.write(tex_source)

        result = subprocess.run(
            ["xelatex", "-interaction=nonstopmode", "-output-directory", tmpdir, tex_path],
            capture_output=True, text=True, timeout=30,
        )

        if result.returncode != 0:
            log_path = os.path.join(tmpdir, "certificate.log")
            log_content = ""
            if os.path.exists(log_path):
                with open(log_path, "r", encoding="utf-8") as f:
                    log_content = f.read()
            raise RuntimeError(
                f"LaTeX compilation failed:\n{result.stderr[:500]}\n{log_content[:1000]}"
            )

        pdf_path = os.path.join(tmpdir, "certificate.pdf")
        if not os.path.exists(pdf_path):
            raise RuntimeError("PDF was not generated by LaTeX")

        with open(pdf_path, "rb") as f:
            return f.read()


def issue_certificate(student, template, issued_by, details="", metadata=None):
    cert = Certificate(
        student=student,
        template=template,
        certificate_number=generate_certificate_number(),
        status="issued",
        issue_date=timezone.now().date(),
        details=details,
        issued_by=issued_by,
        metadata=metadata or {},
    )
    pdf_bytes = generate_certificate_pdf(cert)
    from django.core.files.base import ContentFile
    cert.pdf_file.save(f"{cert.certificate_number}.pdf", ContentFile(pdf_bytes), save=False)
    cert.save()
    return cert
