# Generated by Django 6.0.6 on 2026-07-05 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circles', '0018_circleenrollment_circles_cir_student_e1f1fc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('body', models.TextField(verbose_name='النص')),
                ('audience', models.CharField(choices=[('all', 'كل المستخدمين'), ('role', 'دور محدد'), ('circle', 'حلقة محددة'), ('user', 'مستخدم واحد')], default='all', max_length=10, verbose_name='الجمهور')),
                ('audience_role', models.CharField(blank=True, max_length=20, verbose_name='الدور')),
                ('status', models.CharField(choices=[('queued', 'في الانتظار'), ('sending', 'جارٍ الإرسال'), ('sent', 'أُرسلت'), ('failed', 'فشلت')], db_index=True, default='queued', max_length=10)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('audience_circle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='circles.circle', verbose_name='الحلقة')),
                ('audience_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
            ],
            options={
                'verbose_name': 'حملة بريدية',
                'verbose_name_plural': 'الحملات البريدية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('broadcast', 'رسالة إدارية'), ('approvals', 'اعتماد/رفض حساب'), ('reminders', 'تذكير'), ('updates', 'تحديثات وإعلانات'), ('certificates', 'شهادة')], default='broadcast', max_length=20)),
                ('to_email', models.EmailField(max_length=254, verbose_name='البريد')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('status', models.CharField(choices=[('sent', 'أُرسلت'), ('failed', 'فشلت'), ('skipped', 'متوقفة')], max_length=10)),
                ('error', models.TextField(blank=True, verbose_name='الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='emailcenter.emailcampaign', verbose_name='الحملة')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
            ],
            options={
                'verbose_name': 'سجل بريد',
                'verbose_name_plural': 'سجل البريد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['-created_at'], name='emailcenter_created_1f47a0_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status', '-created_at'], name='emailcenter_status_810393_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['category', '-created_at'], name='emailcenter_categor_081d1a_idx'),
        ),
    ]
