# Generated by Django 6.0.6 on 2026-07-13 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailcenter', '0002_gmailaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='sender_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='emailcenter.gmailaccount', verbose_name='المرسل (Gmail)'),
        ),
    ]
