# Generated by Django 5.1.15 on 2026-06-25 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('technical', 'دعم فني'), ('administrative', 'إداري'), ('academic', 'أكاديمي'), ('other', 'أخرى')], default='other', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'مقدم'), ('under_review', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض'), ('resolved', 'تم الحل')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طلب دعم',
                'verbose_name_plural': 'طلبات الدعم',
                'ordering': ['-created_at'],
            },
        ),
    ]
