# Generated by Django 6.0.6 on 2026-07-04 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['submitted_by', 'status'], name='requests_su_submitt_47bc38_idx'),
        ),
    ]
