# Generated by Django 6.0.6 on 2026-07-03 16:53

import apps.webinars.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('scheduled_at', models.DateTimeField(verbose_name='موعد البث')),
                ('stream_url', models.URLField(blank=True, help_text='رابط YouTube Live (أو ما يعادله) الذي يشاهده الجمهور', max_length=500, verbose_name='رابط البث')),
                ('speaker_room_name', models.CharField(default=apps.webinars.models.generate_speaker_room_name, max_length=64, unique=True, verbose_name='غرفة المتحدثين')),
                ('status', models.CharField(choices=[('scheduled', 'مجدولة'), ('live', 'مباشرة'), ('ended', 'منتهية'), ('replay', 'إعادة')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('co_speakers', models.ManyToManyField(blank=True, related_name='webinars_speaking', to=settings.AUTH_USER_MODEL, verbose_name='المتحدثون')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webinars_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
            ],
            options={
                'verbose_name': 'ندوة',
                'verbose_name_plural': 'الندوات',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
