# Generated by Django 6.0.6 on 2026-07-03 16:23

import apps.classrooms.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('slug', models.SlugField(default=apps.classrooms.models.generate_room_slug, max_length=32, unique=True, verbose_name='معرف الرابط')),
                ('room_name', models.CharField(default=apps.classrooms.models.generate_room_name, max_length=64, unique=True, verbose_name='اسم غرفة Jitsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('teacher', models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='room', to=settings.AUTH_USER_MODEL, verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'قاعة معلم',
                'verbose_name_plural': 'قاعات المعلمين',
            },
        ),
    ]
