# Generated by Django 6.0.6 on 2026-06-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('late', 'متأخر'), ('absent', 'غائب'), ('excused', 'معذور'), ('left_early', 'انصرف مبكراً'), ('pending_justification', 'بانتظار التبرير')], max_length=30),
        ),
    ]
