# Generated by Django 6.0.6 on 2026-06-27 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_absence_justification_fields'),
        ('circles', '0008_session_location_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAttendanceIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('attending', 'سأحضر'), ('absent', 'سأغيب'), ('undecided', 'لم أقرر بعد')], default='undecided', max_length=20, verbose_name='نية الحضور')),
                ('reason', models.TextField(blank=True, verbose_name='سبب الغياب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_intents', to='circles.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نية حضور',
                'verbose_name_plural': 'نوايا الحضور',
                'unique_together': {('session', 'student')},
            },
        ),
    ]
