# Generated by Django 6.0.6 on 2026-07-02 14:22

from django.db import migrations, models


def migrate_existing_records(apps, schema_editor):
    Attendance = apps.get_model('attendance', 'Attendance')
    db_alias = schema_editor.connection.alias

    # Copy teacher_remark -> teacher_comment
    Attendance.objects.using(db_alias).filter(teacher_remark__gt="").update(
        teacher_comment=models.F("teacher_remark"),
    )

    # pending_justification status -> absent + justification_status=pending
    Attendance.objects.using(db_alias).filter(status="pending_justification").update(
        status="absent",
        justification_status="pending",
        justification_submitted_at=models.F("updated_at"),
    )

    # excused -> justification_status=accepted
    Attendance.objects.using(db_alias).filter(status="excused").update(
        justification_status="accepted",
    )

    # absent records with justification text but justification_status=none -> pending
    Attendance.objects.using(db_alias).filter(
        status="absent", justification__gt="", justification_status="none",
    ).update(
        justification_status="pending",
        justification_submitted_at=models.F("updated_at"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_sessionattendanceintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='justification_status',
            field=models.CharField(choices=[('none', 'لا يوجد'), ('pending', 'قيد المراجعة'), ('accepted', 'مقبول'), ('refused', 'مرفوض')], default='none', max_length=20, verbose_name='حالة التبرير'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='justification_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ تقديم التبرير'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher_comment',
            field=models.TextField(blank=True, verbose_name='تعليق المعلم'),
        ),
        migrations.RunPython(migrate_existing_records, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='attendance',
            name='teacher_remark',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('late', 'متأخر'), ('absent', 'غائب'), ('excused', 'معذور'), ('left_early', 'انصرف مبكراً')], max_length=30),
        ),
    ]
