# Generated by Django 6.0.6 on 2026-07-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_attendance_teacher_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='submitted_before_session',
            field=models.BooleanField(default=False, verbose_name='قدّم قبل الحصة'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('not_responded', 'لم يرد'), ('confirmed', 'مؤكد'), ('present', 'حاضر'), ('absent_unjustified', 'غائب بدون عذر'), ('absent_justified', 'غائب بعذر'), ('late', 'متأخر'), ('absent', 'غائب'), ('excused', 'معذور'), ('left_early', 'انصرف مبكراً')], max_length=30),
        ),
    ]
