# Generated by Django 6.0.6 on 2026-07-04 03:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_submitted_before_session_and_more'),
        ('circles', '0016_session_circles_ses_circle__20d87f_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'status'], name='attendance__student_cb2706_idx'),
        ),
    ]
