# Generated by Django 6.0.6 on 2026-06-26 13:26

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circles', '0003_circle_description_circle_schedule_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الامتحان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('exam_type', models.CharField(choices=[('monthly', 'امتحان شهري'), ('quarterly', 'امتحان فصلي'), ('final', 'امتحان نهائي'), ('quiz', 'اختبار قصير'), ('oral', 'اختبار شفهي')], default='monthly', max_length=30, verbose_name='نوع الامتحان')),
                ('exam_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رمز الامتحان')),
                ('exam_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ الامتحان')),
                ('max_marks', models.FloatField(default=100, verbose_name='الدرجة القصوى')),
                ('pass_percentage', models.FloatField(default=50, verbose_name='نسبة النجاح')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('grading', 'جاري التصحيح'), ('pending_approval', 'بانتظار الاعتماد'), ('completed', 'مكتمل'), ('archived', 'مؤرشف')], default='draft', max_length=30, verbose_name='الحالة')),
                ('auto_publish', models.BooleanField(default=False, verbose_name='نشر تلقائي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exams', to=settings.AUTH_USER_MODEL, verbose_name='المعلم المسند')),
                ('circle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='circles.circle', verbose_name='الحلقة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='المنشئ')),
            ],
            options={
                'verbose_name': 'امتحان',
                'verbose_name_plural': 'الامتحانات',
                'ordering': ['-exam_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'إنشاء'), ('published', 'نشر'), ('marks_entered', 'إدخال درجات'), ('submitted', 'تقديم للاعتماد'), ('approved', 'اعتماد'), ('rejected', 'رفض'), ('completed', 'إكمال'), ('archived', 'أرشفة')], max_length=30, verbose_name='الإجراء')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('marks_snapshot', models.JSONField(blank=True, null=True, verbose_name='لقطة الدرجات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='exams.exam')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_actions', to=settings.AUTH_USER_MODEL, verbose_name='المنفذ')),
            ],
            options={
                'verbose_name': 'سجل اعتماد امتحان',
                'verbose_name_plural': 'سجل اعتماد الامتحانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('exam_published', 'نشر امتحان'), ('marks_entered', 'إدخال درجات'), ('submitted_approval', 'تقديم للاعتماد'), ('marks_approved', 'اعتماد درجات'), ('marks_rejected', 'رفض درجات'), ('reminder', 'تذكير')], max_length=30, verbose_name='النوع')),
                ('sent_via', models.CharField(choices=[('in_app', 'داخل التطبيق'), ('email', 'بريد إلكتروني'), ('both', 'كلاهما')], default='in_app', max_length=20, verbose_name='وسيلة الإرسال')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='الرابط')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='exams.exam')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إشعار امتحان',
                'verbose_name_plural': 'إشعارات الامتحانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الدرجة المحصلة')),
                ('percentage', models.FloatField(editable=False, verbose_name='النسبة المئوية')),
                ('grade', models.CharField(editable=False, max_length=10, verbose_name='التقدير')),
                ('is_passed', models.BooleanField(editable=False, verbose_name='ناجح')),
                ('teacher_notes', models.TextField(blank=True, verbose_name='ملاحظات المعلم')),
                ('private_notes', models.TextField(blank=True, verbose_name='ملاحظات خاصة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_marks', to=settings.AUTH_USER_MODEL, verbose_name='معتمد بواسطة')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_marks', to=settings.AUTH_USER_MODEL, verbose_name='مدخل الدرجة')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درجة امتحان',
                'verbose_name_plural': 'درجات الامتحانات',
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
