# Generated by Django 6.0.6 on 2026-07-02 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammark',
            name='marks_obtained',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='الدرجة المحصلة'),
        ),
    ]
