# Generated by Django 6.0.6 on 2026-07-03 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعدادات مستخدم',
                'verbose_name_plural': 'إعدادات المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='SettingsChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='الإعداد')),
                ('old_value', models.JSONField(null=True, verbose_name='القيمة السابقة')),
                ('new_value', models.JSONField(null=True, verbose_name='القيمة الجديدة')),
                ('is_critical', models.BooleanField(default=False, verbose_name='حرج')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='غُيِّر بواسطة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_changes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المتأثر')),
            ],
            options={
                'verbose_name': 'سجل تغيير إعداد',
                'verbose_name_plural': 'سجل تغييرات الإعدادات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key', '-created_at'], name='usersetting_key_7515e9_idx')],
            },
        ),
    ]
