# Generated by Django 6.0.6 on 2026-06-30 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circles', '0008_session_location_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان التقرير')),
                ('report_type', models.CharField(choices=[('attendance', 'تقرير الحضور'), ('grades', 'تقرير الدرجات'), ('hifz', 'تقرير الحفظ'), ('murajaa', 'تقرير المراجعة'), ('circles', 'تقرير الحلقات'), ('teachers', 'تقرير المعلمين')], max_length=30, verbose_name='نوع التقرير')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], default='pdf', max_length=10, verbose_name='الصيغة')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='مجددول')),
                ('schedule_cron', models.CharField(blank=True, max_length=100, verbose_name='جدولة (Cron)')),
                ('last_generated', models.DateTimeField(blank=True, null=True, verbose_name='آخر توليد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circles.circle', verbose_name='الحلقة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL, verbose_name='المنشئ')),
            ],
            options={
                'verbose_name': 'تقرير محفوظ',
                'verbose_name_plural': 'التقارير المحفوظة',
                'ordering': ['-created_at'],
            },
        ),
    ]
