# Generated by Django 6.0.6 on 2026-06-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('approval', 'اعتماد حساب'), ('rejection', 'رفض حساب'), ('new_user', 'مستخدم جديد'), ('new_request', 'طلب دعم جديد'), ('request_update', 'تحديث طلب دعم'), ('announcement', 'إعلان جديد'), ('review_request', 'طلب مراجعة/تسميع'), ('reschedule_request', 'طلب تعديل موعد'), ('absence_review', 'مراجعة تبرير غياب'), ('certificate', 'شهادة'), ('system', 'إشعار نظام')], max_length=30, verbose_name='النوع'),
        ),
    ]
