# Generated by Django 6.0.6 on 2026-07-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('approval', 'اعتماد حساب'), ('rejection', 'رفض حساب'), ('new_user', 'مستخدم جديد'), ('new_request', 'طلب دعم جديد'), ('request_update', 'تحديث طلب دعم'), ('announcement', 'إعلان جديد'), ('review_request', 'طلب مراجعة/تسميع'), ('reschedule_request', 'طلب تعديل موعد'), ('absence_review', 'مراجعة تبرير غياب'), ('certificate', 'شهادة'), ('session_starting', 'بدء الحصة'), ('system', 'إشعار نظام'), ('task_assigned', 'مهمة حفظ/مراجعة'), ('task_validated', 'اعتماد مهمة')], max_length=30, verbose_name='النوع'),
        ),
    ]
